services:
  mysql:
    image: mysql:8.4
    container_name: mysql84
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: demo
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports: ["3306:3306"]
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

  php:
    build:
      context: ./app
      dockerfile: DockerFile
    container_name: php83
    environment:
      DB_HOST: mysql
      DB_NAME: demo
      DB_USER: app
      DB_PASS: secret
      DB_CHARSET: utf8mb4
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports: ["8080:80"]
    volumes:
      - ./app:/var/www/html:ro
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

# Postgres можеш лишити, але для цієї ЛР він не потрібен
#  postgres:
#    image: postgres:16
#    ...
